name: Build docker image

on:
  push:
    branches: 
      - "**"
      - "!main"
      - "!ft/ci-tests"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd kratos-admin-ui && docker build . --tag ghcr.io/dfoxg/kratos-admin-ui:$(date +%s)